### PR TITLE
Feature/29 create contributor component

### PR DESCRIPTION
**Pull request by WronskiN**
I have created the basic Contributor component. Will update it with the next (#30) task.

### CODE REVIEW

**Review by pawelBareja — APPROVED** [review]
I am ok with it.

As a next step I would just put all peoples' personal data in one file, some json, and adjust whole "feature/29" to populate it with the json data.

**Review by pawelBareja — CHANGES_REQUESTED** [review]
typos in ContributorDetails.js  "...foRtawesome.."

`import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faGithub, faLinkedinIn } from '@fortawesome/free-brands-svg-icons';
import { faGlobe } from '@fortawesome/free-solid-svg-icons';`

**Review by LukasMod — CHANGES_REQUESTED** [review]
Looks like there are missing dependencies for fontAwesome.
As it is on fontawesome.com, import @foRtawesome was the right one:
https://fontawesome.com/how-to-use/on-the-web/using-with/react

**Review by LukasMod — APPROVED** [review]

**Comment by LukasMod** [comment]
Please add right dependencies to package.json

**Comment by WronskiN** [comment]
I have added all dependencies. @pawelBareja can you double check and accept it? Thanks!

**Review by pawelBareja — APPROVED** [review]

**Pull request merged**
